apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cybercom-memcache
  name: cybercom-memcache
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cybercom-memcache
    spec:
      containers:
      - image: memcached
        name: cybercom-memcache
        ports:
        - containerPort: 11211
        resources: {}
      restartPolicy: Always
status: {}
