apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cybercom-api
  name: cybercom-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cybercom-api
    spec:
      containers:
        - env:
            - name: DJANGO_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  key: DJANGO_LOG_LEVEL
                  name: cybercom
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: cybercom
            - name: APPLICATION_TITLE
              valueFrom:
                secretKeyRef:
                  key: APPLICATION_TITLE
                  name: cybercom
            - name: BROKER_USE_SSL
              valueFrom:
                secretKeyRef:
                  key: BROKER_USE_SSL
                  name: cybercom
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  key: LOG_LEVEL
                  name: cybercom
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  key: MONGO_DB
                  name: cybercom
            - name: MONGO_LOG_COLLECTION
              valueFrom:
                secretKeyRef:
                  key: MONGO_LOG_COLLECTION
                  name: cybercom
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_PASSWORD
                  name: cybercom
            - name: MONGO_TOMBSTONE_COLLECTION
              valueFrom:
                secretKeyRef:
                  key: MONGO_TOMBSTONE_COLLECTION
                  name: cybercom
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_USERNAME
                  name: cybercom
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_DEFAULT_PASS
                  name: cybercom
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_DEFAULT_USER
                  name: cybercom
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_DEFAULT_VHOST
                  name: cybercom
            - name: SSL_PATH
              valueFrom:
                secretKeyRef:
                  key: SSL_PATH
                  name: cybercom
            - name: DEFAULT_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DEFAULT_DB_NAME
                  name: cybercom
            - name: DEFAULT_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DEFAULT_DB_HOST
                  name: cybercom
            - name: DEFAULT_DB_USER
              valueFrom:
                secretKeyRef:
                  key: DEFAULT_DB_USER
                  name: cybercom
            - name: DEFAULT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DEFAULT_DB_PASSWORD
                  name: cybercom
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: EMAIL_HOST_PASSWORD
                  name: cybercom
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  key: EMAIL_HOST_USER
                  name: cybercom
            - name: API_DEBUG
              valueFrom:
                secretKeyRef:
                  key: API_DEBUG
                  name: cybercom
            - name: LIBCAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: LIBCAL_CLIENT_ID
                  name: cybercom
            - name: LIBCAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: LIBCAL_CLIENT_SECRET
                  name: cybercom
            - name: ROOM_BOOKING_SIERRA_API_KEY
              valueFrom:
                secretKeyRef:
                  key: ROOM_BOOKING_SIERRA_API_KEY
                  name: cybercom
            - name: ROOM_BOOKING_SIERRA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: ROOM_BOOKING_SIERRA_CLIENT_SECRET
                  name: cybercom
            - name: RABBITMQ_SSL_CACERTFILE
              value: "/ssl/testca/cacert.pem"
            - name: RABBITMQ_SSL_CERTFILE
              value: "/ssl/server/cert.pem"
            - name: RABBITMQ_SSL_KEYFILE
              value: "/ssl/server/key.pem"
            - name: RABBITMQ_SSL_CA_FILE
              value: "/ssl/testca/cacert.pem"
            - name: RABBITMQ_SSL_CERT_FILE
              value: "/ssl/server/cert.pem"
            - name: RABBITMQ_SSL_KEY_FILE
              value: "/ssl/server/key.pem"
          image: culibraries/api-k8s:0.0.5
          name: cybercom-api
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /ssl
              name: ssl-keys
      restartPolicy: Always
      volumes:
        - name: ssl-keys
          secret:
            secretName: cybercom
            items:
              - key: CLIENT_CERT_PEM
                path: client/cert.pem
                mode: 420
              - key: CLIENT_KEY_PEM
                path: client/key.pem
                mode: 420
              - key: TESTCA_CACERT_PEM
                path: testca/cacert.pem
                mode: 420
              - key: CLIENT_MONGO_PEM
                path: client/mongodb.pem
                mode: 420
              - key: SP_CERT_PEM
                path: saml/sp-cert.pem
                mode: 420
              - key: SP_KEY_PEM
                path: saml/sp-key.pem
                mode: 420
              - key: IDP_CERT_PEM
                path: saml/idp-cert.pem
                mode: 420
status: {}
